### ISSUE TITLE
Removing all borders?

### ISSUE THREAD

**Issue by aryaxt** [ruslanskorb/RSDayFlow#88]
I'm having a hard time removing the borders on the cells
- I have a subclass if `RSDFDatePickerView` which overrides `dayCellClass`
- I have a subclass of `RSDFDatePickerDayCell` and overrides `dividerImageColor`
 I'm still getting borders

<img width="369" alt="screen shot 2015-11-27 at 4 21 56 pm" src="https://cloud.githubusercontent.com/assets/3460069/11449255/560ee048-9523-11e5-9a30-faa427e68032.png">

The end result I need is 
<img width="365" alt="screen shot 2015-11-27 at 4 25 21 pm" src="https://cloud.githubusercontent.com/assets/3460069/11449259/8258185e-9523-11e5-9881-af99f88f72d9.png">

Any suggestions would be appreciated

**Comment by ruslanskorb** [comment]
Hi @aryaxt,

I think you need to change the background color of `RSDFDatePickerCollectionView`.
Also I can suggest you to debug UI Hierarchy using standard Xcode debugger. It definitely should help identify the problem.

**Comment by aryaxt** [comment]
Thanks for the response
Ended up overriding the flow layout to get rid of extra spacing

```
private class SearchDatePickerCollectionViewLayout: RSDFDatePickerCollectionViewLayout {
    override init!(direction: RSDFDatePickerCollectionViewLayoutDirection) {
        super.init(direction: direction)
        minimumInteritemSpacing = 0
        minimumLineSpacing = 0
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

public class SearchDatePickerView: RSDFDatePickerView {
    public override func collectionViewLayoutClass() -> AnyClass {
        return SearchDatePickerCollectionViewLayout.self
    }
}
```

**Comment by ruslanskorb** [comment]
Just want to clarify.

The above solution will not work on different devices. Because the **minimum** inter-item spacing and the **minimum** line spacing limits only the **minimum** value, but not limits the **maximum** value.

As I pointed out above a better solution for this problem is to override the background color in subclass of `RSDFDatePickerCollectionView` using the `selfBackgroundColor` method.

If you don't want to use the solution above I would suggest to override `selfMinimumLineSpacing` and `selfMinimumInteritemSpacing` methods of `RSDFDatePickerCollectionViewLayout` instead of overriding the `init` method.
